# Generated by Django 5.2.6 on 2025-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_take_exam',
            field=models.BooleanField(default=False),
        ),
    ]
