# Generated by Django 5.2.6 on 2025-11-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
    ]
