# Generated by Django 5.2.6 on 2025-12-06 20:54

import pickup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_name', models.CharField(max_length=200)),
                ('bearer_phone', models.CharField(max_length=20)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=pickup.models.pickup_default_expires)),
            ],
        ),
    ]
