# Generated by Django 5.2.6 on 2025-11-23 18:11

import django.db.models.deletion
import pickup.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_name', models.CharField(max_length=200)),
                ('bearer_phone', models.CharField(max_length=20)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=pickup.models.pickup_default_expires)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_auths', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_for', to=settings.AUTH_USER_MODEL, to_field='registration_number')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
