# Generated by Django 5.2.6 on 2025-12-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickup', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupauthorization',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_auths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupauthorization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_for', to='users.student'),
        ),
        migrations.AddField(
            model_name='pickupauthorization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
