# Generated by Django 5.2.6 on 2025-12-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_class_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name', 'academic_year'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='order',
        ),
    ]
