# Generated by Django 5.2.6 on 2025-11-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopItem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
