# Generated by Django 5.2.6 on 2025-11-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_shopitem_rename_active_item_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('textbook', 'Textbook'), ('school fee', 'School Fee'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
