# Generated by Django 5.2.6 on 2025-11-18 19:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='applicable_class',
            field=models.CharField(choices=[('playgroup', 'Playgroup'), ('kg1', 'KG 1'), ('kg2', 'KG 2'), ('nursery1', 'Nursery 1'), ('nursery2', 'Nursery 2'), ('nursery3', 'Nursery 3'), ('pry1', 'Primary 1'), ('pry2', 'Primary 2'), ('pry3', 'Primary 3'), ('pry4', 'Primary 4'), ('pry5', 'Primary 5'), ('jss1', 'JSS 1'), ('jss2', 'JSS 2'), ('jss3', 'JSS 3'), ('sss1', 'SSS 1'), ('sss2', 'SSS 2'), ('sss3', 'SSS 3')], default='pry1', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
