# Generated by Django 5.2.6 on 2025-11-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='student',
        ),
    ]
